[workspace]
name = "mojo-playground"
description = "A playground for experimenting with the Mojo 🔥 programming language on macOS arm64"
version = "0.1.0"
authors = ["Franck Rasolo <franckrasolo@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://conda.modular.com/max-nightly"]
platforms = ["osx-arm64"]

[dependencies]
python = "==3.13"
modular = ">=25.4.0,<26"

[pypi-dependencies]
pytest = { version = ">=8.4.1" }
pytest-xdist = { version = ">=3.8.0" }
pytest-mojo = { git = "https://github.com/guidorice/mojo-pytest.git" }

[tasks]
